server:
  port: 8090

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    preferSameZoneEureka: true
    region: china
    availability-zones:
          china: zone-1,zone-2
    serviceUrl:
      zone-1: http://localhost:1111/eureka/
      zone-2: http://localhost:1112/eureka/


