server:
  port: 1110

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: center
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
